### ISSUE TITLE
Need more fonts for East Asia languages

### ISSUE THREAD

**Issue by villivateur** [Victorius-Astral/astral-lust-translations#3]
Now the fonts only support western languages, and, for example, Chinese characters will become boxes with a "?" in it.

I have tried to add a new file `game/chinese_font.rpy` and specific font files to solve this problem:

```rpy
# game/chinese_font.rpy
init 200  python:
    if config.language=='chinese':
        config.font_replacement_map["DejaVuSans.ttf", True, False] = ("fonts/msyh.ttc", True, False)
        config.font_replacement_map["DejaVuSans.ttf", True, True] = ("fonts/msyh.ttc", True, True)
        config.font_replacement_map["DejaVuSans.ttf", False, False] = ("fonts/msyh.ttc", False, False)

translate chinese style default:
    font "fonts/msyh.ttc"
translate chinese python:
    gui.button_text_font = "fonts/msyh.ttc"
    gui.glyph_font = "fonts/msyh.ttc"
    gui.interface_text_font = "fonts/msyh.ttc"
    gui.text_font = "fonts/msyh.ttc"
    gui.name_text_font = "fonts/msyh.ttc"
```

But I think it's not the graceful solution. Some charactors will still not shown.

**Comment by villivateur** [comment]
[msyh.zip](https://github.com/Victorius-Astral/astral-lust-translations/files/8499496/msyh.zip)

And here is the test font.

**Comment by Victorius-Astral** [comment]
The font-related changes are all in tl/None/w_python.rpy, I'll check and
find Chinese font with all characters.

sob., 16 kwi 2022 o 09:46 Villivateur Von ***@***.***>
napisał(a):

**Comment by Victorius-Astral** [comment]
https://fonts.google.com/noto/specimen/Noto+Serif+SC/about?subset=chinese-simplified
Download
this font, and unpack to the game/fonts, I'll do the script and push to
GitHub in two hours.

sob., 16 kwi 2022 o 13:25 Victorius ***@***.***> napisał(a):

**Comment by villivateur** [comment]
Thank you, I'll give it a try.

**Comment by Victorius-Astral** [comment]
Do you translate to Simplified Chinese? Here's fonts that can be used
without additional licensing (
https://fonts.google.com/?subset=chinese-simplified)

sob., 16 kwi 2022 o 13:23 Victorius ***@***.***> napisał(a):
