### ISSUE TITLE
New member for Chinese translation

### ISSUE THREAD

**Issue by Akord12** [Victorius-Astral/astral-lust-translations#4]
Hi, I'm glad to be here working for Chinese translation. Please let me know if I can help :)

**Comment by villivateur** [comment]
Hi, I am now working on `combat/` directory, and you can start with `functions/` directory or complete the `screen/` directory. 

During your translation, you can always check if I have translated something wrong and fix it.

If you are not familiar with Git work flow, please refer to some tutorials first, thank you.

@Akord12

**Comment by Akord12** [comment]
Hi, I made a few tries, and realizing maybe we should first make agreement on how some high frequency words are translated. such as health, sanity... Those appears in screen/menu/inventory.rpy may also appears in other places. Kindly let me know if you translated them before.
BTW would you prefer english or chinese in our communication?

**Comment by villivateur** [comment]
You can check files such as `\tl\chinese\variables\classes\Player.rpy`.

For high frequency words, I think we should always search for them in the project first to check if they have already been translated.

I prefer English for common communication.

**Comment by villivateur** [comment]
We should talk at Discord, you can contact me by username villivateur.
